[package]
name = "usboip_driver_linux"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp = "0.8.10"
rmp-serde = "1.0.0"
rusb = "0.9.0"

# Add Linux kernel module crate? TODO.

[dependencies.tokio]
version = "1.16.1"
features = ["rt", "net", "io-util"]
