[package]
name = "usboip-driver-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.0"

# Add Linux kernel module crate? TODO.

[dependencies.tokio]
version = "1.16.1"
features = ["rt", "net", "io-util"]

[dependencies.usboip-protocol]
path = "../../protocol"
