[package]
name = "usbvip-driver-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.1"

# Add Linux kernel module crate? TODO.

[dependencies.tokio]
version = "1.17.0"
features = ["rt", "net", "io-util"]

[dependencies.usbvip-protocol]
path = "../../protocol"
