[package]
name = "usboip-driver-macos"
version = "0.1.0"
edition = "2021"

[dependencies]

# TODO: macOS USB (userland) driver, use XCode and bindgen

[dependencies.tokio]
version = "1.16.1"
features = ["full"]

[dependencies.usboip-protocol]
path = "../../protocol"
