[package]
name = "usboip_driver_macos"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp = "0.8.10"
rmp-serde = "1.0.0"

# TODO: macOS USB (userland) driver, use XCode and bindgen

[dependencies.tokio]
version = "1.16.1"
features = ["full"]
