[package]
name = "usbvip-driver-macos"
version = "0.1.0"
edition = "2021"

[dependencies]

# TODO: macOS USB (userland) driver, use XCode and bindgen

[dependencies.usbvip-protocol]
path = "../../protocol"
